#!/bin/bash

## Script to check and report MegaRAID health for Nagios/Icinga Monitoring System
## Version: 2.1 20191013
## Author: Seff P.

MEGACLIS="/sbin/MegaCli /usr/sbin/MegaCli"


if ! grep -q megaraid /proc/bus/pci/devices
	then
	echo "UNKNOWN: No MegaRAID Controller detected"
	exit 3
fi

for BIN_PATH in $MEGACLIS
do
	if [ -f "$BIN_PATH" ]
	then
		MEGACLI=$BIN_PATH
	fi
done

if [ -z "$MEGACLI" ]
	then
	echo "UNKNOWN: MegaCli command not found"
	exit 3
fi

if ! which sudo &> /dev/null
	then
	echo "UNKNOWN: sudo command required"
	exit 3
fi

RAID_OUTPUT=$(sudo $MEGACLI -LDInfo -Lall -aALL -NoLog && sudo $MEGACLI -PdList -aALL -NoLog)
RAID_STATE=$(echo "$RAID_OUTPUT" | awk '/^State/ {print $NF}' | uniq)
SLOT_IDS=$(echo "$RAID_OUTPUT" | awk '/Slot Number/ {print $NF}')
ENC_ID=$(echo "$RAID_OUTPUT" | awk '/Enclosure Device ID/ {print $NF;exit}')
LEVEL=($(echo "$RAID_OUTPUT"| grep -i "RAID Level" | grep -o [0-9]))
let LEVEL=(${LEVEL[0]}+${LEVEL[1]}*${LEVEL[1]})

for SLOT_ID in ${SLOT_IDS}
	do
	DEVICE_OUTPUT=$(echo "$RAID_OUTPUT" | sed -n "/Slot Number: ${SLOT_ID}/,/Inquiry Data/p")
	DEVICE_ID[$SLOT_ID]=$(echo "$DEVICE_OUTPUT" | awk '/Device Id:/ {print $3}')
	SN[$SLOT_ID]=$(echo "$DEVICE_OUTPUT" | awk '/Inquiry Data/ {print $3}')
	DRIVE_STATE[$SLOT_ID]=$(echo "$DEVICE_OUTPUT" | awk -F ":" '/Firmware state/ {print $2}')
	MEC[$SLOT_ID]=$(echo "$DEVICE_OUTPUT" | awk '/Count: / && !/^Other/ {SUM += $4} END {print SUM}')
	if [[ "${DRIVE_STATE[$SLOT_ID]}" =~ Rebuild ]]
		then
		REBUILD_STATUS=$(sudo $MEGACLI -PDRbld -ShowProg -PhysDrv [${ENC_ID}:${SLOT_ID}] -aALL -NoLog | grep -i "Rebuild")
		REBUILD_DEVICE=$SLOT_ID
	elif [[ "${DRIVE_STATE[$SLOT_ID]}" =~ Online ]]
		then
		OK_DEVICE[$SLOT_ID]=$SLOT_ID
	else
		CRIT_DEVICE=$SLOT_ID
	fi
	if [[ ${MEC[$SLOT_ID]} != 0 ]]
		then
		WARN_DEVICE=$SLOT_ID
	fi
done

if [ "$REBUILD_DEVICE" ]
	then
	STATUS="WARNING: ${REBUILD_STATUS} S/N: ${SN[${REBUILD_DEVICE}]}"
	EXIT=1
elif [ "${CRIT_DEVICE}" ]
	then
	STATUS="CRITICAL: RAID${LEVEL} is $RAID_STATE. Slot #${CRIT_DEVICE}, Device ID #${DEVICE_ID[${CRIT_DEVICE}]} is${DRIVE_STATE[${CRIT_DEVICE}]}. S/N: ${SN[${CRIT_DEVICE}]}"
	EXIT=2
elif [ "${WARN_DEVICE}" ]
	then
	STATUS="WARNING: Slot #${WARN_DEVICE[*]}, Device ID #${DEVICE_ID[${CRIT_DEVICE}]} reported ${MEC[${WARN_DEVICE}]} media errors. S/N: ${SN[${WARN_DEVICE}]}"
	EXIT=1
else
	IFS=','
	STATUS="OK: RAID${LEVEL} is $RAID_STATE. All ${#OK_DEVICE[*]} disks are healthy. S/N: ${SN[*]}"
	EXIT=0
fi
echo "$STATUS"
exit "$EXIT"
